log:
  # debug, info, warn, error
  level: 'debug'
  # colored, text, json
  type: 'colored'
  # if true, will show the source of the log (file and line)
  showSource: true

http:
  # http api bind port
  port: 42069

redict:
  # redict address with port
  address: 'localhost:6379'
  # redict password
  password: 'password'
  # redict db, whatever that means
  db: 7

public:
  # allow public usage?
  enabled: true
  # a list of the domains it may use
  allowedDomains:
    - localhost:42069

apps:
  testing:
    # enable this app?
    enabled: true
    # api key used by the app
    apiKey: 8140e244-0f44-42e1-a7b2-295e53e2b334
    # a list of the domains it may use
    allowedDomains:
      - localhost:42069
