name: CI/CD
on:
  push:
    branches:
      - master

jobs:
  build_test_inspect:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout code
        uses: https://github.com/actions/checkout@v4

      - name: Set up Go
        uses: https://github.com/actions/setup-go@v5
        with:
          go-version: '>=1.24.0'

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Install inspection tools
        run: make install-inspect-tools

      - name: Inspect
        run: make inspect

  deploy:
    needs: [build_test_inspect]
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: https://github.com/actions/checkout@v3

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: https://github.com/docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: Log in to Docker Registry
        uses: https://github.com/docker/login-action@v2
        with:
          registry: code.db.cafe
          username: pauloo27
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set short git commit SHA
        id: vars
        run: |
          echo "COMMIT_SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v4
        env:
          ACTIONS_RUNTIME_TOKEN: ''
        with:
          file: Dockerfile
          context: .
          push: true
          tags: code.db.cafe/pauloo27/shurl:${{ env.COMMIT_SHORT_SHA }},code.db.cafe/pauloo27/shurl:${{ github.ref_name }}

      - name: Upgrade install 
        uses: https://code.db.cafe/actions/k7z-upgrade@v1.1.0
        with:
          base_url: https://k7z.db.cafe/api/v0
          team_name: pauloo27
          project_name: shurl
          api_key: ${{ secrets.K7Z_SECRET }}
          ref: ${{ github.ref_name }}
          data: '{"Tag":"${{ env.COMMIT_SHORT_SHA }}"}'

