// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Get the health status of the server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.HealthStatus"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/health.HealthStatus"
                        }
                    }
                }
            }
        },
        "/links": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a link from a slug to the original URL.\nIf no slug is provided, a random one will be generated.\nThe ttl is required. 0 means no expiration, otherwise it's the number of seconds until expiration.\nThe ttl can't be greater than 1 year (31536000 seconds).\nThe API Key may limit the ttl.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "Create a link",
                "parameters": [
                    {
                        "description": "Slug is optional",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/link.CreateLinkBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "API Key, leave empty for public access (if enabled in the server)",
                        "name": "X-API-Key",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Link"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.Error-map_string_string"
                        }
                    },
                    "401": {
                        "description": "Missing API Key",
                        "schema": {
                            "$ref": "#/definitions/api.Error-map_string_string"
                        }
                    },
                    "403": {
                        "description": "Invalid API Key",
                        "schema": {
                            "$ref": "#/definitions/api.Error-map_string_string"
                        }
                    },
                    "409": {
                        "description": "Duplicated link",
                        "schema": {
                            "$ref": "#/definitions/api.Error-map_string_string"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/api.Error-map_string_string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Error-map_string_string"
                        }
                    }
                }
            }
        },
        "/{slug}": {
            "get": {
                "description": "Redirect from domain/slug to the original URL",
                "tags": [
                    "link"
                ],
                "summary": "Redirect to the original URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug to redirect from",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    },
                    "404": {
                        "description": "Link not found",
                        "schema": {
                            "$ref": "#/definitions/api.Error-map_string_string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Error-map_string_string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Error-map_string_string": {
            "type": "object",
            "properties": {
                "detail": {
                    "$ref": "#/definitions/map_string_string"
                },
                "error": {
                    "type": "string",
                    "example": "NOT_FOUND"
                }
            }
        },
        "health.HealthStatus": {
            "type": "object",
            "properties": {
                "rdb": {
                    "type": "boolean"
                }
            }
        },
        "link.CreateLinkBody": {
            "type": "object",
            "required": [
                "original_url"
            ],
            "properties": {
                "original_url": {
                    "type": "string"
                },
                "slug": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "ttl": {
                    "type": "integer",
                    "maximum": 31536000,
                    "minimum": 0
                }
            }
        },
        "map_string_string": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "models.Link": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "original_url": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "ttl": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Shurl API",
	Description:      "URL Shortener API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
