basePath: /api/v1
definitions:
  health.HealthStatus:
    properties:
      rdb:
        type: boolean
    type: object
info:
  contact: {}
  description: URL Shortener API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Shurl API
  version: "1.0"
paths:
  /healthz:
    get:
      description: Get the health status of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.HealthStatus'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/health.HealthStatus'
      summary: Get health status
      tags:
      - Health
swagger: "2.0"
