name: Shurl

repos:
  - name: dbcafe-base
    url: https://code.db.cafe/api/packages/dbcafe/helm

installs:
  - name: shurl
    chart: dbcafe-base/public-app

  - name: valkey
    chart: oci://registry-1.docker.io/bitnamicharts/valkey
    chartVersion: '2.3.0'

envs:
  - name: prod
    namespace: shurl
    for: 
      branch: master
    values: 
      - values/common.yaml
      - values/prod.yaml

  - name: dev
    namespace: shurl-dev
    for:
      branch: dev
    values: 
      - values/common.yaml
      - values/dev.yaml
