image:
  tag: dev

imageUpdater:
  enabled: true
  images:
    shurl:
      imageName: "code.db.cafe/pauloo27/shurl:dev"
      updateStrategy: "digest"
      namePattern: "shurl-dev"
  writeBackMethod: "argocd"

externalSecrets:
  shurl-config-secret:
    data:
      - secretKey: config.yaml
        sourceRef:
          storeRef:
            name: openbao
            kind: ClusterSecretStore
        remoteRef:
          key: shurl-dev/shurl-config-secret
          property: config.yaml

istio:
  enabled: true
  host: url-dev.db.cafe
